### ISSUE TITLE
Models / migration maken voor game 

### ISSUE THREAD

**Issue by syberen** [syberen/wend-foosball#2]

**Comment by Jasper-Koops** [comment]
Bij users gaan we waarschijnlijk custom velden tracken toch? (Elo score, record doelpunten per match, keren sander verslagen, highest ranking in onze ranglijst) 

[Er zijn verschillende manieren om in Django velden aan een user toe te voegen ](https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html)

Ik ga zelf meestal voor optie 4 (extending abstract user) - voor deze app zal het niet superveel verschil maken, maar bij teacherschannel loop ik sporadisch tegen issues aan met one-to-one profile relations, proxy models hebben een relatief trage query en bij AbstractBaseUser moeten we alle fijne delen van Django vervangen door iets wat waarschijnlijk precies het zelfde gaat doen.

**Comment by syberen** [comment]
Ok dan stel ik de volgende database structuur voor om mee te beginnen:
- users
- players (1 on 1 met users)
- player-game koppeltabel met ook positie (voor of achter) en team van de speler
- games

**Comment by SuperDoxin** [comment]
Ik zou mischien de player-game koppeltabel anders doen, Ik zou bij een game eigenlijk gewoon 4 foreign keys zetten: team 1 spits, team 1 defense, team 2 spits, team 2 defense. Many-to-many is wat overdreven en django gaat ook slecht om met koppeltabellen met extra data. Maar verder prima, Ik hoor het wel als je pr klaar is ;)

**Comment by syberen** [comment]
@SuperDoxin lijkt me ook prima
